### ISSUE TITLE
Call to undefined function error when PMPro core is not active.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-member-directory#118]
When `paid-memberships-pro` plugin is not active `pmpro-member-directory` causes a fatal PHP error.

**Steps to recreate**

1. Navigate to Plugins > All Plugins and deactivate Paid Memberships Pro plugin.
2. See `There has been a critical error on this website. Please check your site admin email inbox for instructions.` notification
3. See debug log `PHP Fatal error:  Uncaught Error: Call to undefined function pmpro_getOption() in /path/wp-content/plugins/pmpro-member-directory/pmpro-member-directory.php:538`

**Comment by michaelbeil** [comment]
Reported in this ticket (ID 426901).
>I also got the following fatal error when I disabled the plugins to check for conflicts and tried to reactivate them.
![image](https://user-images.githubusercontent.com/4752949/172942391-99546d92-46c5-463a-ba98-f2c6f074f8b8.png)

**Comment by JarrydLong** [comment]
This PR has been queued up and will be released soon to fix this https://github.com/strangerstudios/pmpro-member-directory/pull/124
