### ISSUE TITLE
Bug: Using multiple directory pages causes issues

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-member-directory#119]
Having multiple directory pages causes an issue - when trying to view a single profile you get redirected away. 

How to recreate: 

1. Create multiple directory pages with different level params
2. Don't set a directory page in the page settings
3. Visit one of the directory pages and click on a profile

Expected behavior: We need to work out how to handle a directory that has multiple directory pages. Setting the directory page to a specific directory page doesn't fix this. 

Ticket for reference (mods only) https://www.paidmembershipspro.com/forums/topic/bad-update-of-member-directory-plugin/

**Comment by MaryOJob** [comment]
Same issue: Moderators only: #419030

**Comment by JarrydLong** [comment]
Tested this further and reviewed current logic for how the new profile functionality is handled. 

Having multiple directory pages and not setting a directory page **will not** cause an issue for when viewing a profile. 

As long as a single profile page is set under Memberships > Settings > Pages this will work as expected. 

In the event of this not working, we would need to investigate and debug as it could be a site specific issue - possibly caused by overriding a profile template. 

Closing this issue.
