### ISSUE TITLE
BUG: Hide from member directory label - backend and front end

### ISSUE THREAD

**Issue by vondigital** [strangerstudios/pmpro-member-directory#122]
*possible bug* @andrewlimaza 

After the recent update, we are seeing the label for the 'Hide from member directory' checkbox displaying an incorrect label.

WP Dashboard - User Profile
![image](https://user-images.githubusercontent.com/70516283/165742737-44b2fbc4-c02a-496e-a08b-61e36e93b039.png)
This used to say:  Hide from Member Directory.
Now it shows: Hide from {Current logged in username}

Front end - PMPro Profile page (pmpro-member-profile-edit)
![image](https://user-images.githubusercontent.com/70516283/165743117-17b0bd12-c949-41ec-b84e-0d365c4ab612.png)
This used to say:  Hide from Member Directory
Now it shows:  Hide from {page title}

Appreciate any feedback on this.
Thanks

**Comment by andrewlimaza** [comment]
Thanks for bringing this to our attention, we will continue to look into this further as it should show the title of the Directory Page. Here's the code for reference: https://github.com/strangerstudios/pmpro-member-directory/blob/dev/pmpro-member-directory.php#L82

**Comment by andrewlimaza** [comment]
I'm unable to replicate this, would you mind opening up a support ticket on www.paidmembershipspro.com and our team will investigate this further.
