### ISSUE TITLE
Font size Display name

### ISSUE THREAD

**Issue by sacrefizz** [strangerstudios/pmpro-member-directory#137]
how to change Display name size?

**Comment by andrewlimaza** [comment]
Hi @sacrefizz 

Thanks for reaching out here, we don't offer support questions on Github and may take us some time to get a reply to issues.

You would need to use CSS to adjust the font-size of the display name. The CSS class `.pmpro_member_directory_name` may be used, as well as `.pmpro_member_directory_display-name` (for the directory page).

For future support queries or help with this, please open a support ticket at www.paidmembershipspro.com/support
