### ISSUE TITLE
Custom Fields for checkbox_grouped save option id # instead of value

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-member-directory#145]
**Describe the bug**
When using custom code to create user taxonomies:
https://www.paidmembershipspro.com/store-user-profile-fields-custom-user-taxonomy/#user-taxonomies
An option is given to use 'checkbox_grouped`.  The `checkbox_grouped` displays the answers as ID # and not the value. The other field types, select, select2, and radio, do save display as expected.
 
**To Reproduce**
1. Create user Taxonomies
https://github.com/strangerstudios/pmpro-snippets-library/blob/dev/user-fields/custom-user-taxonomy-field.php
2. Add taxonomy entries
3. Go through the Checkout
4. Add field to the directory or profile. They is displayed as numbers.

**Screenshots**
![Screenshot 2023-03-07 at 12 11 20 PM](https://user-images.githubusercontent.com/8083630/223520401-9de8791c-eb42-488d-835c-63da08b32839.png)

**Comment by andrewlimaza** [comment]
Adding a note here, I moved this to the Directory repository.

**Comment by andrewlimaza** [comment]
This PR fixes this too (for group checkboxes) - https://github.com/strangerstudios/pmpro-member-directory/pull/146
