### ISSUE TITLE
PHP8 Warning returned if Profile Page configured to unplubished post.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-member-directory#150]
**Describe the bug**

When a profile page option was set and the status of the page thereafter was changed to an unpublished state a PHP8 Warning is generated when visiting the directory page.

```
PHP Warning:  preg_match(): Compilation failed: quantifier does not follow a repeatable item at offset 1 in /path-to-root/wp-includes/class-wp.php on line 234
PHP Warning:  preg_match(): Compilation failed: quantifier does not follow a repeatable item at offset 1 in /path-to-root/wp-includes/class-wp.php on line 235
```

This issue only occurs if the server is running PHP8, not for older versions, and only if the profile page is not set correctly to a published page on the page settings for PMPro core (Memberships > Settings > Pages)

**To Reproduce**
1. Go to Memberships > Settings > Pages and confirm that a published page is set for the "Profile" page.
2. Go to Pages, select the set profile page and change the status to draft.
3. Go to the frontend member directory page.
4. See error displayed on page or in debug log if WP Debug is enabled and set to logging.

**Expected behavior**
No PHP warning returned

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kimcoleman** [comment]
This will be fixed in https://github.com/strangerstudios/pmpro-member-directory/blob/q4-2024-cycle/templates/profile.php
