### ISSUE TITLE
Feature: Creating a more Filterable and Searchable Function

### ISSUE THREAD

**Issue by AnsieLima** [strangerstudios/pmpro-member-directory#19]
There has been a couple of requests coming in to have a more advanced search function according to member profiles fields and custom fields. 

For example, they would like to filter the custom fields that they create like age, location or specific interests.

**Comment by andrewlimaza** [comment]
The current search functionality will search via meta_key (custom field) values.

So if the user has user meta of 'age = 19' and you search 19. This will return all users that have this meta value. It doesn't search according to meta_key. I'll write up a blog post on how to improve on this, it does require some custom code to achieve but it is doable :)

**Comment by andrewlimaza** [comment]
We are merging an update that will allow developers to easily adjust the SQL query for the directory results. This will also allow people to adjust the search queries etc.
