### ISSUE TITLE
Filter for "View Profile" link

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-member-directory#21]
Users may want to filter the url that the "View Profile" link directs to, perhaps to the bbPress or BuddyPress profile page if they are using these plugins.

We could add a filter to the url here for modifying:
https://github.com/strangerstudios/pmpro-member-directory/blob/master/templates/directory.php#L35

**Comment by andrewlimaza** [comment]
Pull Request -> https://github.com/strangerstudios/pmpro-member-directory/pull/24
