### ISSUE TITLE
PHP Warnings: Viewing Profile for a non-member

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-member-directory#23]
When viewing the front-end profile for a non-member, there is a warning when the shortcode attempts to output the start and end dates. We should account for this and either redirect away from the Profile page if no level is found or hide those fields from trying to output.

**Comment by greathmaster** [comment]
PR https://github.com/strangerstudios/pmpro-member-directory/pull/25 will redirect if attempting to access non-member user profiles.

**Comment by andrewlimaza** [comment]
Going to run some tests for this.

**Comment by andrewlimaza** [comment]
This is fixed.
