### ISSUE TITLE
Missing Page Title when No Directory Page is Set on Edit User Profile

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-member-directory#26]
When you have just installed the plugin and have not created or assigned a page for your directory, the setting on the Edit User page should either not be shown or a default title should be used here:

https://github.com/strangerstudios/pmpro-member-directory/blob/master/pmpro-member-directory.php#L56

Without this, the setting looks like this:
<img width="590" alt="Screen Shot 2019-05-28 at 2 25 55 PM" src="https://user-images.githubusercontent.com/5312875/58502589-cbec2e80-8154-11e9-8185-309cd31e0590.png">

**Comment by femiyb** [comment]
https://github.com/femiyb/pmpro-member-directory/tree/5.4
