### ISSUE TITLE
New CSS Layouts not IE11 Compatible

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-member-directory#47]
A user reported that the new CSS grid-based column layout is not compatible in IE11. I have not confirmed this but will complete some tests and do a PR for a fallback method with this browser.

**Comment by kimcoleman** [comment]
A user shared the following code that is tested and working with ie11. I'm going to also run tests and see if this is the best path:

`/* PM PRO MEMBER DIRECTORY CSS */

h3#pmpro_member_directory_subheading {clear: none; margin-top: 0; }
form.pmpro_member_directory_search {float: right; margin-bottom: 1rem; clear: both; }
form.pmpro_member_directory_search input[type=text] { }
form.pmpro_member_directory_search input[type=submit] {background: none; border: none; padding: 0; position: absolute; text-indent: -9999em; }

.pmpro_member_directory {clear: both; }
.pmpro_pagination {margin: 1em 0;}
.pmpro_pagination .pmpro_prev {float: left; width: 250px;}
.pmpro_pagination .pmpro_next {float: right; width: 250px; text-align: right;}

/* div/column type layouts */
div.pmpro_member_directory div h3 {clear: none; }
div.pmpro_member_directory div p {margin: .5rem 0 0 0; } 
div.pmpro_member_profile strong {display: block; }

/* table type layouts */
.pmpro_member_directory table h3.pmpro_member_directory_display-name {margin-top: 0; }
.pmpro_member_directory table tbody td {vertical-align: top; }
.pmpro_member_directory table tbody td p {margin: 0 0 .5rem 0; }

/* column type layouts */
.pmpro_member_directory.pmpro_member_directory-2col,
.pmpro_member_directory.pmpro_member_directory-3col,
.pmpro_member_directory.pmpro_member_directory-4col {
    display: -ms-grid;
    display: grid;
    grid-column-gap: 2.9rem;
    grid-row-gap: 5.8rem;
    column-gap: 2.9rem;
    row-gap: 5.8rem;
    text-align: center;
}
.pmpro_member_directory.pmpro_member_directory-2col {
    -ms-grid-columns: 1fr 1fr;
    grid-template-columns: 1fr 1fr;
}
.pmpro_member_directory.pmpro_member_directory-3col {
    -ms-grid-columns: 1fr 1fr 1fr;
    grid-template-columns: 1fr 1fr 1fr;
}
.pmpro_member_directory.pmpro_member_directory-4col {
    -ms-grid-columns: 1fr 1fr 1fr 1fr;
    grid-template-columns: 1fr 1fr 1fr 1fr;
}

/* [ IE11 ]  */

_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-2col,
_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-3col,
_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-4col {
	display: block;
}


_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-2col .pmpro_member_directory-item,
_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-3col .pmpro_member_directory-item,
_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-4col .pmpro_member_directory-item { 
	display: block;
	position: relative;
    padding-left: 1em;
    padding-right: 1em;
    float: left;
    padding-bottom: 5.8rem;
}

_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-2col .pmpro_member_directory-item {
	width: 50%;
}

_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-3col .pmpro_member_directory-item {
	 width: 33.33333%;
}

_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-4col .pmpro_member_directory-item {
	 width: 25%;
}


@media only screen and (max-width: 980px) {
    .pmpro_member_directory.pmpro_member_directory-2col,
    .pmpro_member_directory.pmpro_member_directory-3col {
        -ms-grid-columns: 1fr;
        grid-template-columns: 1fr;
    }
    
    _:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-2col .pmpro_member_directory-item {
	 	width: 100%;
	}
	
	_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-2col .pmpro_member_directory-item {
		clear: left;
	}
    
    .pmpro_member_directory.pmpro_member_directory-4col {
        -ms-grid-columns: 1fr 1fr;
        grid-template-columns: 1fr 1fr;
    }
    
    _:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-3col .pmpro_member_directory-item,
    _:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-4col .pmpro_member_directory-item {
	 	width: 50%;
	}
	
}

@media only screen and (max-width: 639px) {
    .pmpro_member_directory.pmpro_member_directory-4col {
        -ms-grid-columns: 1fr;
        grid-template-columns: 1fr;
    }
    
    _:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-3col .pmpro_member_directory-item,
    _:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-4col .pmpro_member_directory-item {
	 	width: 100%;
	 	clear: left;
	}

}

@media only screen and (min-width: 640px) and (max-width: 980px)  {

	_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-3col .pmpro_member_directory-item:nth-child(odd),
	_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-4col .pmpro_member_directory-item:nth-child(odd) {
		clear: left;
	}
}


@media only screen and (min-width: 981px) {
	_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-2col .pmpro_member_directory-item:nth-child(odd),
	_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-3col .pmpro_member_directory-item:nth-child(3n + 1),
	_:lang(x)::-ms-backdrop, .pmpro_member_directory.pmpro_member_directory-4col .pmpro_member_directory-item:nth-child(4n + 1) {
		clear: left;
	}
	
}`

**Comment by andrewlimaza** [comment]
I think it's okay to not support IE. Microsoft has announced it's no longer an active browser.

**Comment by JarrydLong** [comment]
I've discussed this with Kim, briefly in points: 

- Due to the low usage of IE11 we're going to close this
- Lets bring this up in a cycle discussion in the future
- Monitor and see if it becomes an issue again, then lets open again and take it from there.
