### ISSUE TITLE
In Admin Dashboard, the Pages link redirects to Member Directory

### ISSUE THREAD

**Issue by andrewwoods** [strangerstudios/pmpro-member-directory#48]
Here's the problem. When I'm in the WordPress Dashboard, I get redirected to my Membership Directory page when I click the 'Pages' link. 

**Expected**:
    To see the list of WordPress Pages. 

**Actual**:
    Redirected to the Membership Page

This is a weird bug. I don't think this was intended. But here's how to re-create it

* Install the base PMPro plugin. 
* Install the "Member Directory Add On". 
* Select a page to be your membership directory.
* In the left nav of the WordPress Dashboard, click 'Pages'

You'll be redirected to your membership directory page in your theme.

My fix for the problem is add the following code to the top of the `pmpromd_profile_preheader()` function in **wp-content/plugins/pmpro-member-directory/templates/profile.php**

```php
if (is_admin()){
    return;
}
```

**Comment by kimcoleman** [comment]
Hi there,

I am trying to recreate this issue and I cannot. Are you still having this issue without the edit you made to your file?

Can you clarify if you have assigned both the Directory and Profile pages to a unique page under Memberships > Settings > Page Settings? Does each of these pages have the correct shortcode or block in place?

What version of Paid Memberships Pro and the Member Directory Add On are you using? Are you using any custom templates or just the default layouts?

**Comment by JarrydLong** [comment]
There's been a couple of major changes in the profile.php template in Version 1.2 and this issue is about 2 years old, so I'm going to close this issue. If the issue persists please open a support ticket so that we can investigate further.
