### ISSUE TITLE
State and Country shortcode displaying in abbreviated format

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-member-directory#52]
A user reported that the state and country fields in their shortcode is displaying in abbreviated format on the member directory page. Hence instead of showing for instance `Canada`, it shows `CA`. I have recreated this and can confirm the two fields show in abbreviated formats.

**Comment by andrewlimaza** [comment]
This is due to how the fields are stored in the database, we would need to map these fields to their labels.

**Comment by JarrydLong** [comment]
I don't think we'll add support for all those fields TBH, but, I'm going to add in a filter (mentioned in #93) so that we can at least filter the value and handle the states from the State Dropdown Add On instead.
