### ISSUE TITLE
Search breaks when using apostrophes

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-member-directory#55]
As per this topic: https://www.paidmembershipspro.com/forums/topic/apostrophe-escaping-in-search/

When searching for a member and using an apostrophe, slashes aren't stripped and no results are found. 

Tested using: 
PMPro 2.2.6
WP 5.3.2
Member Directory: .6.1

**Comment by kimwhite** [comment]
The issue with the apostrophe is when it's a CURLY apostrophe.  search does not recognize it as a standard apostrophe.
