### ISSUE TITLE
Multi-language

### ISSUE THREAD

**Issue by paramedicquebec** [strangerstudios/pmpro-member-directory#6]
Can you activate multi-language for this plug-in? Thanks!

**Comment by eighty20results** [comment]
Hi,

We've got I18N support being included in the latest pull request for Jason to review and apply (hopefully) or reject ( :( ).

**Comment by paramedicquebec** [comment]
Any update on this? I really need to translate it in french!

**Comment by montrealist** [comment]
Any news on this so far?

**Comment by strangerstudios** [comment]
This is now available in version .5
