### ISSUE TITLE
Feature Request: Add "edit profile" link to Member Profile when logged in.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-member-directory#60]
Add "edit profile" link to Member Profile when logged in.
I have done this by customizing the profile template

**Comment by kimcoleman** [comment]
I like the update - would be really helpful for users. We would only want to show it if they are viewing their own profile (maybe show for administrator and go to edit profile in dashboard?).

we can make it a shortcode attribute or filter to hide it.

**Comment by kimcoleman** [comment]
should we only show this link if they are using the frontend member profile edit page? should we link to the WordPress profile page if ours is not set using the same logic like: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/shortcodes/pmpro_account.php#L165-L172
