### ISSUE TITLE
Filter to optionally not do embed, format site_url, or make hyperlinks clickable

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-member-directory#67]
The directory and profile templates currently have some special handling for user meta or user object fields that show as a single line links in a few spots such as:

-  https://github.com/strangerstudios/pmpro-member-directory/blob/dev/templates/directory.php#L531
-  https://github.com/strangerstudios/pmpro-member-directory/blob/dev/templates/directory.php#L538
-  https://github.com/strangerstudios/pmpro-member-directory/blob/dev/templates/directory.php#L366

This issue is to request a filter for each time we run the special treatment of field user_url, "wp_oembed_get", or "make_clickable" and allow each to be disabled so only the URL appears.  It may be best to always fall back to "make_clickable" rather than wp_oembed_get or the formatting user_url.

**Comment by kimcoleman** [comment]
Some links people may want to turn into an embed, such as a YouTube or another type of media. Whatever we choose here let's make sure that there is a way to allow some embeds for certain URLS.

Side note -  the URL itself becomes an embed when its another WordPress site and I believe may rely on JetPack. Need to confirm this.

**Comment by kimcoleman** [comment]
This is connected to this other issue: https://github.com/strangerstudios/pmpro-member-directory/issues/90

If we have a filter, run it on the user_email field as well as any meta fields.

**Comment by JarrydLong** [comment]
This was reworked in https://github.com/strangerstudios/pmpro-member-directory/pull/111
