### ISSUE TITLE
Feature Request: Allow Logged in User to see their own profile even if "Hide from directory" is checked.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-member-directory#85]
If the Member has opted out of the directory view, we would want them to be able to preview what their public Directory Profile page would look like.

**Comment by kimcoleman** [comment]
This could cause some confusion and I think right now we want to hold off.

A workaround would be to filter the pmpromd_hide_directory user meta field before its returned to set to true under the appropriate conditions. This is where that redirect happens:

https://github.com/strangerstudios/pmpro-member-directory/blob/dev/templates/profile.php#L29-L36

You could use this WordPress filter to override and always return a value of true/1 for that usermeta field: https://developer.wordpress.org/reference/functions/get_metadata_raw/
