### ISSUE TITLE
get_userdata doesn't return usermeta fields from Register Helper fields

### ISSUE THREAD

**Issue by contemplate** [strangerstudios/pmpro-member-directory#9]
For some reason the latest update to PMPro Register Helper disabled the added fields from displaying on the Member Directory.  It appears the get_userdata() isn't returning all the usermeta fields.  

I've done the following to patch this:
File: plugins/pmpro-member-directory/templates/directory.php

Replace both instances of this:
`$meta_field = $auser->$field[1];`

with this:
`$meta_field = get_user_meta( $auser->ID, $field[1], false );`

**Comment by kimcoleman** [comment]
This is resolved in version .5
