### ISSUE TITLE
Output the label value for checkbox custom fields

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-member-directory#93]
We should output the label value or make it filterable to do this when outputting Register Helper checkbox fields or if the field value is '1'.

This still needs some thought how to handle custom fields not created by Paid Memberships Pro.

**Comment by dwanjuki** [comment]
A customer ran into this issue. 
Ticket #493657 (Moderators)

**Comment by andrewlimaza** [comment]
Making a note here, I wouldn't output the label but rather "Yes" or "No" based on that value.

This PR fixes for other custom fields that store key => label pairs (https://github.com/strangerstudios/pmpro-member-directory/pull/146)

It would be best to adjust the function (in PMPro core) `pmpro_get_label_for_user_field_value` to support checkboxes and not hacky PR here.

**Comment by andrewlimaza** [comment]
Just a FYI, this doesn't work with associative arrays correctly. Due to a limitation in the `pmpro_get_label_for_user_field_value` function skipping over associative arrays.
