### ISSUE TITLE
Submit button is disabled in profile edit

### ISSUE THREAD

**Issue by edraculet** [strangerstudios/pmpro-member-directory#94]
I've made a fix for the issue described in PR https://github.com/strangerstudios/pmpro-member-directory/pull/92
Can someone have a look and maybe merge the fix?

Thank you!

**Comment by kimcoleman** [comment]
This would be an update for the core Paid Memberships Pro plugin, not this Member Directory plugin. Please open an issue on the main PMPro repository to discuss this: https://github.com/strangerstudios/paid-memberships-pro/
